[versions]
activity = "1.12.1"
activityCompose = "1.12.1"
agp = "8.13.2"
androidxComposeBom = "2025.12.00"
annotation = "1.9.1"
appcompat = "1.7.1"
coilCompose = "3.3.0"
dagger = "2.57.2"
datastorePreferences = "1.2.0"
fragment = "1.8.9"
dependency-analysis = "3.5.1"
espressoCore = "3.7.0"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
junit = "4.13.2"
junitVersion = "1.3.0"
ksp = "2.3.2"
kotlin = "2.2.21"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationCore = "1.9.0"
ktlint = "14.0.1"
compose-rules-ktlint-version = "0.5.2"
leakcanaryAndroid = "2.14"
lifecycle = "2.10.0"
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
okhttp = "5.3.2"
paging = "3.3.6"
retrofit = "3.0.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
room = "2.8.4"
runner = "1.7.0"
sqlite = "2.6.2"
timber = "5.0.1"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-animation-core = { module = "androidx.compose.animation:animation-core" }
androidx-animation = { module = "androidx.compose.animation:animation" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom-alpha", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-lifecycle-livedata-core = { module = "androidx.lifecycle:lifecycle-livedata-core", version.ref = "lifecycle" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-gradle-plugin = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }
androidx-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-unit = { module = "androidx.compose.ui:ui-unit" }
androidx-ui-text = { module = "androidx.compose.ui:ui-text" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
compose-rules-ktlint = { module = "io.nlopez.compose.rules:ktlint", version.ref = "compose-rules-ktlint-version" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }